spring:
  application:
    name: discovery-server
  config:
#    import: 'optional:configserver:http://192.168.1.31:9090'
    import: 'optional:configserver:${config-server}'
  profiles:
    active: dev
